### ISSUE TITLE
[Tainted] Acedium tantes Embeddium on 1.20.1

### ISSUE THREAD

**Issue by Cartrigger** [ferriarnus/acedium#26]
From using this mod, because nothing much is changed, Embeddium picks up on it and "taints" it, making it of course warn in logs that the game is tainted and to not ask for support.

**Comment by ferriarnus** [comment]
yes, this is "normal". Embeddium added a mixin detector since to many mods mixin to embeddium and cause issues. The log warning is meant so the player would recreate it without the mod, and if that isn't possible, to report it to the offending mod. At this time, I can not make it not taint embeddium, since the api's needed are to complex at the moment.
